server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
      config:
        server:
          git:
            uri: https://github.com/Stephen201202/microservicecloud-config.git # GitHub上git仓库名字