server:
  port: 9527

spring:
   application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url: # 客户端注册进eureka服务列表内
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:  # 修改服务名称
    instance-id: gateway-9527.com  # 自定义服务名称信息
    prefer-ip-address: true  # 访问路径可以显示IP地址

#  原访问：http://myzuul.com:9527/microservicecloud-dept/dept/get/2
#  现访问：http://myzuul.com:9527/quhao/dept/get/1
#  避免微服务名直接暴露
zuul:
  routes:
    my.serviceId: microservicecloud-dept
    my.path: /quhao/**
  ignored-services: "*"  # 隐藏微服务名